workflows:
  release-android:
    name: Release Android Build
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Create google-services.json
        script: |
          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk