org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=512m
org.gradle.daemon=false
android.enableJetifier=true
android.useAndroidX=true
android.enableR8=true
org.gradle.parallel=false
org.gradle.configureondemand=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
